// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpbn8jkdknI39k8arbwasDHtFFBfg_a_w',
    appId: '1:749134591992:web:34ecd9d16148dba09b880d',
    messagingSenderId: '749134591992',
    projectId: 'ara-service',
    authDomain: 'ara-service.firebaseapp.com',
    storageBucket: 'ara-service.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdcuf5_VrZj1DgJf9fQ17TohxW1aEqY7I',
    appId: '1:749134591992:android:53ddaed3c02fe6bc9b880d',
    messagingSenderId: '749134591992',
    projectId: 'ara-service',
    storageBucket: 'ara-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4kDvWrXI9SKdKgJnu620SKTeGT9tXng',
    appId: '1:749134591992:ios:af5b47e8ce02360a9b880d',
    messagingSenderId: '749134591992',
    projectId: 'ara-service',
    storageBucket: 'ara-service.firebasestorage.app',
    androidClientId: '749134591992-sp90t0n24elbi6otegkfp2vurinepju6.apps.googleusercontent.com',
    iosClientId: '749134591992-h9a5k4lbdqnhfrrav31i8crmb6lolndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.araadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI4kDvWrXI9SKdKgJnu620SKTeGT9tXng',
    appId: '1:749134591992:ios:af5b47e8ce02360a9b880d',
    messagingSenderId: '749134591992',
    projectId: 'ara-service',
    storageBucket: 'ara-service.firebasestorage.app',
    androidClientId: '749134591992-sp90t0n24elbi6otegkfp2vurinepju6.apps.googleusercontent.com',
    iosClientId: '749134591992-h9a5k4lbdqnhfrrav31i8crmb6lolndt.apps.googleusercontent.com',
    iosBundleId: 'com.example.araadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpbn8jkdknI39k8arbwasDHtFFBfg_a_w',
    appId: '1:749134591992:web:b50cc33896efcefe9b880d',
    messagingSenderId: '749134591992',
    projectId: 'ara-service',
    authDomain: 'ara-service.firebaseapp.com',
    storageBucket: 'ara-service.firebasestorage.app',
  );
}
